### ISSUE TITLE
Prepare the SR2023 Compstate

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1045]
The competition software has state about the competition which is used to drive the matches, live displays of scores (etc.) both within the venue on the website.
This task is to create the initial state for the competition; see https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#create-a-compstate and https://github.com/search?q=topic%3Acompstate+org%3Asrobo&type=Repositories.

### Original

[comp/ops/compstate](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/compstate.yaml)

### Dependencies

 * [x] #986
 * [x] #1004
 * [ ] #1037 Design the SR2023 knockouts
 * [ ] #1038 Schedule the league matches
 * [x] #1039 Create SR2023 game score format
 * [x] #1040 Write scoring scripts for the SR2023 game
 * [ ] #1041 Organise shepherding
 * [ ] #1042 Prepare the Compbox
 * [x] #1043 Work out layout of teams at the competition
 * [x] #1044 Deploy a public compbox

**Comment by PeterJCLaw** [comment]
Baseline created at https://github.com/srobo/sr2023-comp. Needs a scorer adding and review of the timings etc.

**Comment by WillB97** [comment]
Blocked on #1038
