### ISSUE TITLE
Update the website for the live SR2023 physical competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1057]
There are website alterations to be made to enable its use live at the competition.

https://github.com/srobo/tasks/issues/1156 exists separately for the virtual competition.

### Original

[comp/website/main](https://github.com/srobo/recurring-tasks/blob/master/comp/website/main.yaml)

### Dependencies

 * [ ] #975
 * [ ] #1044 Deploy a public compbox
 * [ ] #1045 Prepare the SR2023 Compstate
 * [ ] #1046 Publish day schedule on website
 * [ ] #1052 Put stream on website
 * [ ] #1053 Switch the website (proxy) to Competition Live mode
 * [ ] #1054 Uprate the competitor-services server _before_ the competition starts
 * [ ] #1055 Publish SR2023 layout maps
 * [ ] #1056 Put directions to the venue on the website
