### ISSUE TITLE
Create score data entry system (update the scorer UI)

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1107]
We need a data entry system for converting from the score entry forms to the YAML file format.
This task is both the root for preparing this system and covers the updating of the scorer UI for this year's game.
See https://github.com/PeterJCLaw/srcomp/wiki/Competition-Preparation#implement-updatehtml and  for details of the latter.

### Original

[comp/game/score-entry](https://github.com/srobo/recurring-tasks/blob/master/comp/game/score-entry.yaml)

### Dependencies

 * [ ] #1017
 * [ ] #1039 Create SR2023 game score format
 * [ ] #1040 Write scoring scripts for the SR2023 game
 * [ ] #1106 Get desk lamp for score entry
