### ISSUE TITLE
Deploy the score entry system

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1111]
The machine which will be used for score entry need setting up. At least one of these is expected to be a permanent machine placement.
This should also include confirming that the relevant pages and ops software things can be accessed.

### Original

[comp/ops/deploy-score-entry](https://github.com/srobo/recurring-tasks/blob/master/comp/ops/deploy-score-entry.yaml)

### Dependencies

 * [ ] #997
 * [ ] #1068 Provide network to the arena
 * [ ] #1069 Provide power to the arenas
 * [ ] #1107 Create score data entry system (update the scorer UI)

**Comment by WillB97** [comment]
This covered in the setup schedule #1140
