### ISSUE TITLE
Update the website for the live SR2023 virtual competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#1156]
There are website alterations to be made to enable its use live at the virtual competition.

### Dependencies

 * [x] #1044 Deploy a public compbox
 * [x] #1045 Prepare the SR2023 Compstate
 * [x] #1052 Put stream on website
 * [ ] #1154
 * [x] https://github.com/srobo/tasks/issues/973

**Comment by PeterJCLaw** [comment]
Aside from the mode swapping this is now done.
