### ISSUE TITLE
Setup the 2019 Compstate

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#119]
Aside from the baseline structure, this relies on:
* [x] configuring the arenas (we only have one this year)
* [x] importing the teams names & rookie statuses
* [x] the overall schedule (#73) - to know what the timeslots for the matches are
* [x] creating the scoring logic (#111), which is blocked on knowing what the scoring input is going to be, which derives from the scoring UI (#108) which is blocked on the score-sheets (#109)
* [x] knowing the layout of the teams #65 & #211, in order to populate the shepherding info (see also #114)
* [x] knowing the league match plan (#103)
* [x] knowing the knockouts plan (#102)
* [x] configuring the deployments (#118, #233)

**Comment by PeterJCLaw** [comment]
I've made a start at this at https://github.com/srobo/sr2019-comp. I'd actually thought I needed to do that in order to have a repo to put the score sheet in (#109), but ended up putting that in the arena repo instead.

**Comment by WillB97** [comment]
Given that it takes over a minute to walk from the cafe area to the cube it may be worth increasing the time ahead that shepherds get notified.

**Comment by PeterJCLaw** [comment]
Historically the shepherds have communicated via radio and/or Slack, with each one remaining fixed in a particular area. The time allowances are therefore for a one-way trip (the one the teams make).

That said, the numbers here are copy/pasted from those for a different venue, so I have no idea how good they are for SUSU. Suggestions of what would be suitable warning times for each part of the venue (as well as suitable zone delineations) would be most welcome.

**Comment by PeterJCLaw** [comment]
For the moment there's not a lot more progress we can make on this.
Blockers:
* creating the scoring logic (#111), which is blocked on knowing what the scoring input is going to be, which derives from the scoring UI (#108) which is blocked on the score-sheets (#109)
* knowing the layout of the teams #64, in order to populate the shepherding info (see also #114)
* knowing the league match plan (#103)
* knowing the knockouts plan (#102)
