### ISSUE TITLE
Create/update visual assets for SR2024 livestream

### ISSUE THREAD

**Issue by antonnikitin97** [srobo/tasks#1351]
```[tasklist]
### Tasks
- [ ] Check/update sponsors slides
- [ ] Virtual competition highlights reel
- [ ] Update rules slides
- [ ] Create rules "scenario videos" for presentation
- [ ] Challenges highlights reel
```

**Comment by PeterJCLaw** [comment]
The livestream happened.
