### ISSUE TITLE
Print remaining things

### ISSUE THREAD

**Issue by WillB97** [srobo/tasks#1354]
Some key items were not ready for the main print run and still need printing.

The outstanding items are:
 - [ ] Safety notes sheets x 2
 - [x] Safety check certificates?
 - [x] Risk Assessments (setup & competition) x 1
 - [ ] ~~Helpdesk documentation x 2~~
 - [x] Award cards
 - [x] Pit Rules
```[tasklist]
### Tasks
- [ ] https://github.com/srobo/tasks/issues/1306
```
