### ISSUE TITLE
Do Alistair shit

### ISSUE THREAD

**Issue by prophile** [srobo/tasks#1356]
- [x] Match schedule
- [x] Knockout design/checks
- [x] Time checks
- [x] Primary checklists
- [x] Sync teams into srcomp
- [x] Figure out awards process
- [x] Test arena plan
- [x] Robot inspection checklist
- [x] Operational concept
- [x] Training plan
- [x] Write safety briefing for chaperones
- [x] Figure out match flow
- [x] Staging layout
- [x] Ops team shift roles
```[tasklist]
### Tasks
- [ ] https://github.com/srobo/tasks/issues/1264
- [ ] https://github.com/srobo/tasks/issues/1312
- [ ] https://github.com/srobo/tasks/issues/1315
- [ ] https://github.com/srobo/tasks/issues/1263
```
