### ISSUE TITLE
Pack the team kits

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#21]
Once everything is tested and prepared we need to pack the kits.

See https://github.com/srobo/tasks/milestone/2 for sub-tasks.

The kit packing session has happened, though we now need to put the wire (#35) into each of the kits:
- [x] London Kickstart teams (#39)
- [x] Southampton Kickstart teams (#40)
- [x] other teams (#41)
- [ ] un-munge the kits which were swapped from in Southampton (#50)

**Comment by Tyler-Ward** [comment]
One kit in southampton has a broken board in it, was swapped during the micro-games

**Comment by PeterJCLaw** [comment]
This is essentially done, the remaining kit (in #50) is going out for a second team at a school and needs sorting, but keeping this ticket open serves not benefit around that.
