### ISSUE TITLE
Collate the SR2019 kits

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#283]
We need to clean & tidy the kits which were issued for SR2019, plus test them so we know which need fixing before the next competition.

This is documented as a ["Kit Collation Event"](https://srobo.github.io/runbook/kit/hardware/kit-collation/).

As we've not yet got all the kits back, this likely means several events - this task is a parent and should remain open until all kit is accounted for.

Sub Tasks:
- [x] #284 First collation event
- [x] ~#285 Kit return pack for HRS (optional)~
- [x] #301 Second collation event
- [x] #303 Third collation event
- [ ] Fourth collation event
- [ ] #297 Chase teams for missing kit

**Comment by PeterJCLaw** [comment]
@TomWheal I think you mentioned that you're owning sorting the kits for SR2020. With that in mind, are you expecting that you'll also take on [collating] (cleaning, testing etc.) the remaining kits from SR2019? If so, would you like to grab this task?

[collating]: https://srobo.github.io/runbook/kit/hardware/kit-collation/

**Comment by PeterJCLaw** [comment]
(I don't have capacity to do this at the moment)

**Comment by PeterJCLaw** [comment]
Broad summary of the current state:
* three kits were never returned (see also #297)
* @RealOrangeOne has 2-3 kits which haven't yet been collated
* I believe the inventory is correct about the state of items which have been collated (in terms of condition/physical_condition)
* the inventory may also record the cleaned/inspected/etc. state through subfolders; if it doesn't have subfolders any more, then the history of the items definitely will

From what I recall in terms of progress:
* most of the returned kit has been inspected & cleaned & re-labelled as needed, some has been tested
* some kit was loaned back out to SourecBots for the summer school; that kit should likely be considered needing re-testing etc.

**Comment by TomWheal** [comment]
Only just come across this task, feel free to assign this to me.

**Comment by PeterJCLaw** [comment]
> Only just come across this task, feel free to assign this to me.

Thanks!

(meta: you should be able to self-assign -- was there anything which prevented you from doing so? Asking as we have had some challenges getting the permissions right here)

**Comment by RealOrangeOne** [comment]
> @RealOrangeOne has 2-3 kits which haven't yet been collated

There's actually 4 kits with me (inventory is up-to-date). As i'm intending to be at the next collation event, I'm more than happy to bring them along also!

(meta: RE perms, I've check and permissions are all setup correctly as i'd expect)

**Comment by TomWheal** [comment]
> (meta: you should be able to self-assign -- was there anything which prevented you from doing so? Asking as we have had some challenges getting the permissions right here)

I don't always have access to a computer and came across it on my phone. The 3rd party app I'm using doesn't seem to support that.

**Comment by TomWheal** [comment]
All the kit has been collated, except missing stuff
