### ISSUE TITLE
Prepare kits for the SR2020 Kickstart

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#353]
We need to have kits to hand out at the SR2020 Kickstart.

### Original

[kickstart/kit/main](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/main.yaml)

### Dependencies

 * #315 Test kits for SR2020
 * #317 Fix any issues with the kits for SR2020
 * #325 Allocate SR2020 kits to teams
 * #334 Ship SR2020 kits to Kickstarts
 * #343 Ship SR2020 kits to Teams not attending Kickstarts
 * #352 Ship SR2020 kits to overseas Teams

**Comment by PeterJCLaw** [comment]
@TomWheal since you're the Kit Team representative owning this, would you like to take this task? Feel free to adapt it and it's dependants as needed if you do.

**Comment by TomWheal** [comment]
I'm going to post updates on the organisation of this in this thread:

- Dates and Times: Friday 4th October 5pm till Sunday 6th 5pm.

- Two venues have been organised, The Annex 2 Large lecture theatres, and 2 large rooms in Mountbatten(Seminar Room and Postgrad Common Room). Both have areas that can be locked overnight for kit storage.  (Actual Venue will depend on the number of volunteers)

- Email is in the works for Inviting Volunteers to help. 

### ToDo

- [ ] Finish Email Inviting Volunteers

- [ ] Workout how many rubs need bringing to Southampton to determine if we need a van to move stuff
- [ ] Create the workflow for tasks needed on the day.

- [ ] Confirm what consumables will be bought before the kit prep weekend, and get budget approved.

I will not be creating more GitHub tasks for these as they are apart of preparing this and don't require more notification spam. I'll keep on updating progress here

**Comment by TomWheal** [comment]
Note: 
#325 Allocate SR2020 kits to teams
#334 Ship SR2020 kits to Kickstarts
#343 Ship SR2020 kits to Teams not attending Kickstarts
#352 Ship SR2020 kits to overseas Teams

Can someone in the competition team pick this up, it is outside the scope of the kit team in my opinion

**Comment by RealOrangeOne** [comment]
@TomWheal for context, what is "this"? Is it the linked issues in that comment? If so I think you're right that they fall under the Competition Team to deal with.

**Comment by TomWheal** [comment]
Yeh sorry poor wording on my part, yeh the ones linked in the comment.

**Comment by TomWheal** [comment]
40 Kits have been packed. The 19 that will go to the container tomorrow have sensitive components in jiffy bags, they have not been stuffed with bubble wrap for shipping tho. The other 21 are in my garage, which i will deliver to the soton kickstart. The 3 kit team volunteers going to one of the 3 kickstarts also have a spare kit box, which they'll bring with them.

**Comment by TomWheal** [comment]
I think so 👏

**Comment by PeterJCLaw** [comment]
Meta: in general I've been expecting that parent issues such as this would remain open until all their children are complete.
