### ISSUE TITLE
Create microgames for the SR2020 Kickstart

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#388]
At Kickstart we usually have the teams perform some introductory tasks to get them familiar with the kit and to establish that they can safely charge their batteries.
The tasks also help give them a starting point in programming and familiarity with asking Blueshirts for help.
Examples from previous years:
 - [SR2019](https://docs.google.com/document/d/13-zZVXi3YbPEgqVuGP8RA-t9qiHk2rBW4SbcU5_WepY/edit)
 - [SR2017](https://drive.google.com/drive/folders/0B-WfTB1zV9sza3BSMU1LeHBSNVE?usp=sharing)
 - [SR2016](https://drive.google.com/open?id=1T-JOaAeUpG1JWr8pmnM7bD1PB3RV0d3Pkzp4z-FHrEU)
 - [SR2015](https://docs.google.com/document/d/19YdjD7thAmS1A09UGYC5D7L_8qqyXl1BupXFottsadI/edit)

### Original

[kickstart/microgames](https://github.com/srobo/recurring-tasks/blob/master/kickstart/microgames.yaml)

### Dependencies

 * #354 Decide on the SR2020 game

### TODO

* [x] update obfuscated `print`
* [x] sort out short urls https://github.com/srobo/infrastructure/issues/4
* [x] update theming
* [x] prepare supporting documents

**Comment by sedders123** [comment]
I have started work on this years microgames, they can be found in the Kickstart folder on [Google Drive](https://docs.google.com/document/d/1Dm4AEqdvozhJcu9kRDULOOE-ZE2Y_JnepB2LfWgz19Q/edit?usp=sharing). So far have just copied last years but will go through and refine as necessary. 

I intend to either replace or make simpler the ultrasound task as many people have said teams found this very complicated, another option would be to leave it as is but give it a higher complexity level. Interested to know what others think about this.

**Comment by RealOrangeOne** [comment]
@sedders123 do the microgames we have require any specialized equiptment to do? If so we're going to need to ensure those are taken to kickstarts (https://github.com/srobo/tasks/issues/405). Although for logistical reasons, we should really try and minimize that as much as possible!

**Comment by Adimote** [comment]
I've finished V1.0 of the microgames. I'd be happy to print them now but it'd be nice to add another task. Reviews welcome!

**Comment by PeterJCLaw** [comment]
These are now happening.
