### ISSUE TITLE
Get the non-kit items from the container

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#405]
We need to get the non-kit items required for kickstart from the container.

(It's possible these items aren't in the container)

## Items
- [ ] Tablecloths
- [ ] Servos (For microgames)
- [ ] Ultrasound Sensors (For microgames)
- [ ] T-shirts (To be given to London and Cambridge kickstarts)

## Tasks
- [ ] Check the size of the arena pieces (take a tape measure)

**Comment by PeterJCLaw** [comment]
@RealOrangeOne are you going to be visiting the container any time soon? If so, would it make sense for you to pick these up then?

**Comment by RealOrangeOne** [comment]
This is blocked on a plan on how we're getting the remaining kit to the kickstart venues (#334). Once that's worked out, we can work out if and how we're going to do this.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne I think this is done now?

**Comment by RealOrangeOne** [comment]
I think it is. 

Servos, ultrasound, some tokens and LEDs are either at or on their way to the kickstart locations.
